version: "2"
exclude_patterns:
- ".ebextensions/"
- "config/"
- "db/"
- "doc/"
- "features/"
- "log/"
- "public/"
- "script/"
- "spec/"
- "test/"
- "tmp/"
- "vendor/"
- "app/assets/javascripts/"
- "!app/assets/javascripts/application.js"
- "!app/assets/javascripts/aws-upload.js"
- "**/*.css"
- "**/*.png"
- "**/*.gif"
- "**/*.jpeg"
- "**/*.txt"
- "**/*.md"
- "**/*.markdown"
- "**/*.yml"
- "**/*.example"
- "**/*.travis"
- "**/*.feature"
- "**/*.old"
- "**/*.rake"
- "**/*.config"
- "**/*.lock"
- "**/*.docker"
- "**/*.sh"
- "**/*.ru"
- "**/*.erb"
- ".autotest"
- ".dockerignore"
- ".gitignore"
- ".ruby-version"
- "Capfile"
- "Dockerfile"
- "Gemfile"
- "Rakefile"
- ".codeclimate.yml"
- ".travis.yml"
