version: "2"
exclude_patterns:
- "public/**/*.js"
- "app/assets/javascripts/effects.js"
- "app/assets/javascripts/fancybox.js"
- "app/assets/javascripts/jquery-cycle.js"
- "app/assets/javascripts/jquery-jnotify.js"
- "app/assets/javascripts/jquery-noconflict.js"
- "app/assets/javascripts/jquery-progressbar.js"
- "app/assets/javascripts/jquery-ui-1.8.4.js"
- "app/assets/javascripts/mousewheel.js"
- "app/assets/javascripts/prototype.js"
- "app/assets/javascripts/swfobject.js"
- "app/assets/javascripts/video-js-5.4.6.js"