sudo: false

language: ruby

rvm:
  - 2.5.1

dist: trusty

env:
  global:
    - CC_TEST_REPORTER_ID=3b2f52dc3b63783aff82025781069d594a929078f42db7e21726f854836085d8
    - COVERAGE_REPORT=true

addons:
  apt:
    packages:
    # the version of dpkg is old in this version of ubunutu and the latest build
    # of chrome now requires the updated dpkg, I'm not sure if the oder of the
    # addons will always work here.
    - dpkg
  chrome: stable

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cp config/database.yml.travis config/database.yml
  - cp config/aws.yml.travis config/aws.yml
  - bundle clean # TODO: remove after upgrade - this is here to ensure no old gems stick around during upgrade
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - "export DISPLAY=:99.0"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache: bundler
