version: '3'
services:
  app:
    build:
      context: .
    command: ./docker-run.sh
    volumes:
      - .:/vpb:delegated
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: xyzzy
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: xyzzy
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      # use a named volume here so the database is preserved after a down and up
      - mysql:/var/lib/mysql
volumes:
  bundle:
  mysql:
