# this is for testing the production server setup locally (more info in readme)
version: '3'
services:
  # uses different app name to keep bundle output separate from dev app
  prod_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm /vpb/tmp/unicorn.pid; ./docker/prod/prod-run.sh"
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: xyzzy
      DEVISE_SECRET_KEY:
      SECRET_KEY_BASE:
      ACCESS_KEY_ID:
      SECRET_ACCESS_KEY:
      S3_BUCKET:
      S3_REGION:
      PIPELINE_ID:
      RDS_DB_NAME:
      RDS_USERNAME:
      RDS_PASSWORD:
      RDS_HOSTNAME:
      RDS_PORT:
      SES_KEY:
      SES_SECRET:
      MAILER_HOSTNAME:
      DEBUG_PRODUCTION:
      ALLOWED_HOSTS:
  # uses same db volume as dev app
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: xyzzy
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      # use a named volume here so the database is preserved after a down and up
      - mysql:/var/lib/mysql
volumes:
  mysql:
