source :gemcutter

gem 'bundler'
gem 'rails', '2.3.8'
gem 'mysql'
gem 'capybara'
gem 'database_cleaner'
gem 'cucumber-rails'
gem 'cucumber'
gem 'rspec-rails'
gem 'spork'
gem 'launchy'
gem 'capistrano-ext'
gem 'velir_kaltura-ruby', :require=> 'kaltura'
gem 'devise', '1.0.7'
gem 'devise_invitable', '0.2.3'
gem 'warden'
gem 'factory_girl', '1.2.4'
