# DO NOT MODIFY THIS FILE
# Generated by Bundler 0.9.25

require 'digest/sha1'
require 'yaml'
require 'pathname'
require 'rubygems'
Gem.source_index # ensure Rubygems is fully loaded in Ruby 1.9

module Gem
  class Dependency
    if !instance_methods.map { |m| m.to_s }.include?("requirement")
      def requirement
        version_requirements
      end
    end
  end
end

module Bundler
  class Specification < Gem::Specification
    attr_accessor :relative_loaded_from

    def self.from_gemspec(gemspec)
      spec = allocate
      gemspec.instance_variables.each do |ivar|
        spec.instance_variable_set(ivar, gemspec.instance_variable_get(ivar))
      end
      spec
    end

    def loaded_from
      return super unless relative_loaded_from
      source.path.join(relative_loaded_from).to_s
    end

    def full_gem_path
      Pathname.new(loaded_from).dirname.expand_path.to_s
    end
  end

  module SharedHelpers
    attr_accessor :gem_loaded

    def default_gemfile
      gemfile = find_gemfile
      gemfile or raise GemfileNotFound, "Could not locate Gemfile"
      Pathname.new(gemfile)
    end

    def in_bundle?
      find_gemfile
    end

    def env_file
      default_gemfile.dirname.join(".bundle/environment.rb")
    end

  private

    def find_gemfile
      return ENV['BUNDLE_GEMFILE'] if ENV['BUNDLE_GEMFILE']

      previous = nil
      current  = File.expand_path(Dir.pwd)

      until !File.directory?(current) || current == previous
        filename = File.join(current, 'Gemfile')
        return filename if File.file?(filename)
        current, previous = File.expand_path("..", current), current
      end
    end

    def clean_load_path
      # handle 1.9 where system gems are always on the load path
      if defined?(::Gem)
        me = File.expand_path("../../", __FILE__)
        $LOAD_PATH.reject! do |p|
          next if File.expand_path(p).include?(me)
          p != File.dirname(__FILE__) &&
            Gem.path.any? { |gp| p.include?(gp) }
        end
        $LOAD_PATH.uniq!
      end
    end

    def reverse_rubygems_kernel_mixin
      # Disable rubygems' gem activation system
      ::Kernel.class_eval do
        if private_method_defined?(:gem_original_require)
          alias rubygems_require require
          alias require gem_original_require
        end

        undef gem
      end
    end

    def cripple_rubygems(specs)
      reverse_rubygems_kernel_mixin

      executables = specs.map { |s| s.executables }.flatten
      Gem.source_index # ensure RubyGems is fully loaded

     ::Kernel.class_eval do
        private
        def gem(*) ; end
      end

      ::Kernel.send(:define_method, :gem) do |dep, *reqs|
        if executables.include? File.basename(caller.first.split(':').first)
          return
        end
        opts = reqs.last.is_a?(Hash) ? reqs.pop : {}

        unless dep.respond_to?(:name) && dep.respond_to?(:requirement)
          dep = Gem::Dependency.new(dep, reqs)
        end

        spec = specs.find  { |s| s.name == dep.name }

        if spec.nil?
          e = Gem::LoadError.new "#{dep.name} is not part of the bundle. Add it to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        elsif dep !~ spec
          e = Gem::LoadError.new "can't activate #{dep}, already activated #{spec.full_name}. " \
                                 "Make sure all dependencies are added to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        end

        true
      end

      # === Following hacks are to improve on the generated bin wrappers ===

      # Yeah, talk about a hack
      source_index_class = (class << Gem::SourceIndex ; self ; end)
      source_index_class.send(:define_method, :from_gems_in) do |*args|
        source_index = Gem::SourceIndex.new
        source_index.spec_dirs = *args
        source_index.add_specs(*specs)
        source_index
      end

      # OMG more hacks
      gem_class = (class << Gem ; self ; end)
      gem_class.send(:define_method, :bin_path) do |name, *args|
        exec_name, *reqs = args

        spec = nil

        if exec_name
          spec = specs.find { |s| s.executables.include?(exec_name) }
          spec or raise Gem::Exception, "can't find executable #{exec_name}"
        else
          spec = specs.find  { |s| s.name == name }
          exec_name = spec.default_executable or raise Gem::Exception, "no default executable for #{spec.full_name}"
        end

        gem_bin = File.join(spec.full_gem_path, spec.bindir, exec_name)
        gem_from_path_bin = File.join(File.dirname(spec.loaded_from), spec.bindir, exec_name)
        File.exist?(gem_bin) ? gem_bin : gem_from_path_bin
      end
    end

    extend self
  end
end

module Bundler
  ENV_LOADED   = true
  LOCKED_BY    = '0.9.25'
  FINGERPRINT  = "949dfceb2682daff3d8157371ad19d9e80b2a0ff"
  HOME         = '/Users/robertps/.bundle/ruby/1.8/bundler'
  AUTOREQUIRES = {:default=>[["capistrano-ext", false], ["capybara", false], ["cucumber", false], ["cucumber-rails", false], ["database_cleaner", false], ["launchy", false], ["mysql", false], ["rails", false], ["rspec-rails", false], ["spork", false], ["kaltura", true]]}
  SPECS        = [
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/rake-0.8.7.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/rake-0.8.7/lib"], :name=>"rake"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/activesupport-2.3.8.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib"], :name=>"activesupport"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/rack-1.1.0.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/rack-1.1.0/lib"], :name=>"rack"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/actionpack-2.3.8.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.3.8/lib"], :name=>"actionpack"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/actionmailer-2.3.8.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.3.8/lib"], :name=>"actionmailer"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/activerecord-2.3.8.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib"], :name=>"activerecord"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/activeresource-2.3.8.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/activeresource-2.3.8/lib"], :name=>"activeresource"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/builder-2.1.2.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/builder-2.1.2/lib"], :name=>"builder"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/highline-1.6.1.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/highline-1.6.1/lib"], :name=>"highline"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/net-ssh-2.0.23.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/net-ssh-2.0.23/lib"], :name=>"net-ssh"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/net-scp-1.0.2.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/net-scp-1.0.2/lib"], :name=>"net-scp"},
        {:loaded_from=>"/Users/robertps/.gem/ruby/1.8/specifications/net-sftp-2.0.4.gemspec", :load_paths=>["/Users/robertps/.gem/ruby/1.8/gems/net-sftp-2.0.4/lib"], :name=>"net-sftp"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/net-ssh-gateway-1.0.1.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/net-ssh-gateway-1.0.1/lib"], :name=>"net-ssh-gateway"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/capistrano-2.5.19.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/capistrano-2.5.19/lib"], :name=>"capistrano"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/capistrano-ext-1.2.1.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/capistrano-ext-1.2.1/lib"], :name=>"capistrano-ext"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/culerity-0.2.10.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/culerity-0.2.10/lib"], :name=>"culerity"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/mime-types-1.16.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/mime-types-1.16/lib"], :name=>"mime-types"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/nokogiri-1.4.2.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/nokogiri-1.4.2/lib"], :name=>"nokogiri"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/rack-test-0.5.4.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/rack-test-0.5.4/lib"], :name=>"rack-test"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/ffi-0.6.3.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/ffi-0.6.3/lib", "/usr/local/lib/ruby/gems/1.8/gems/ffi-0.6.3/ext"], :name=>"ffi"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/json_pure-1.4.3.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/json_pure-1.4.3/lib"], :name=>"json_pure"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/rubyzip-0.9.4.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/rubyzip-0.9.4/lib"], :name=>"rubyzip"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/selenium-webdriver-0.0.27.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/selenium-webdriver-0.0.27/lib"], :name=>"selenium-webdriver"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/capybara-0.3.9.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/capybara-0.3.9/lib"], :name=>"capybara"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/configuration-1.1.0.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/configuration-1.1.0/lib"], :name=>"configuration"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/diff-lcs-1.1.2.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/diff-lcs-1.1.2/lib"], :name=>"diff-lcs"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/trollop-1.16.2.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/trollop-1.16.2/lib"], :name=>"trollop"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/gherkin-2.1.5.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/gherkin-2.1.5/lib"], :name=>"gherkin"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/term-ansicolor-1.0.5.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/term-ansicolor-1.0.5/lib"], :name=>"term-ansicolor"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/cucumber-0.8.5.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/cucumber-0.8.5/lib"], :name=>"cucumber"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/cucumber-rails-0.3.2.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/cucumber-rails-0.3.2/lib"], :name=>"cucumber-rails"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/database_cleaner-0.5.2.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/database_cleaner-0.5.2/lib"], :name=>"database_cleaner"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/json-1.4.3.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/json-1.4.3/ext/json/ext", "/Users/robertps/.bundle/ruby/1.8/gems/json-1.4.3/ext", "/Users/robertps/.bundle/ruby/1.8/gems/json-1.4.3/lib"], :name=>"json"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/launchy-0.3.7.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/launchy-0.3.7/lib"], :name=>"launchy"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/mysql-2.8.1.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/mysql-2.8.1/lib", "/usr/local/lib/ruby/gems/1.8/gems/mysql-2.8.1/ext"], :name=>"mysql"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/rails-2.3.8.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/rails-2.3.8/lib"], :name=>"rails"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/rest-client-1.6.0.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/rest-client-1.6.0/lib"], :name=>"rest-client"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/rspec-1.3.0.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/rspec-1.3.0/lib"], :name=>"rspec"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/rspec-rails-1.3.2.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/rspec-rails-1.3.2/lib"], :name=>"rspec-rails"},
        {:loaded_from=>"/Users/robertps/.bundle/ruby/1.8/specifications/spork-0.8.4.gemspec", :load_paths=>["/Users/robertps/.bundle/ruby/1.8/gems/spork-0.8.4/lib"], :name=>"spork"},
        {:loaded_from=>"/usr/local/lib/ruby/gems/1.8/specifications/velir_kaltura-ruby-0.4.0.gemspec", :load_paths=>["/usr/local/lib/ruby/gems/1.8/gems/velir_kaltura-ruby-0.4.0/lib"], :name=>"velir_kaltura-ruby"},
      ].map do |hash|
    if hash[:virtual_spec]
      spec = eval(hash[:virtual_spec], TOPLEVEL_BINDING, "<virtual spec for '#{hash[:name]}'>")
    else
      dir = File.dirname(hash[:loaded_from])
      spec = Dir.chdir(dir){ eval(File.read(hash[:loaded_from]), TOPLEVEL_BINDING, hash[:loaded_from]) }
    end
    spec.loaded_from = hash[:loaded_from]
    spec.require_paths = hash[:load_paths]
    if spec.loaded_from.include?(HOME)
      Bundler::Specification.from_gemspec(spec)
    else
      spec
    end
  end

  extend SharedHelpers

  def self.configure_gem_path_and_home(specs)
    # Fix paths, so that Gem.source_index and such will work
    paths = specs.map{|s| s.installation_path }
    paths.flatten!; paths.compact!; paths.uniq!; paths.reject!{|p| p.empty? }
    ENV['GEM_PATH'] = paths.join(File::PATH_SEPARATOR)
    ENV['GEM_HOME'] = paths.first
    Gem.clear_paths
  end

  def self.match_fingerprint
    lockfile = File.expand_path('../../Gemfile.lock', __FILE__)
    lock_print = YAML.load(File.read(lockfile))["hash"] if File.exist?(lockfile)
    gem_print = Digest::SHA1.hexdigest(File.read(File.expand_path('../../Gemfile', __FILE__)))

    unless gem_print == lock_print
      abort 'Gemfile changed since you last locked. Please run `bundle lock` to relock.'
    end

    unless gem_print == FINGERPRINT
      abort 'Your bundled environment is out of date. Run `bundle install` to regenerate it.'
    end
  end

  def self.setup(*groups)
    match_fingerprint
    clean_load_path
    cripple_rubygems(SPECS)
    configure_gem_path_and_home(SPECS)
    SPECS.each do |spec|
      Gem.loaded_specs[spec.name] = spec
      spec.require_paths.each do |path|
        $LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
      end
    end
    self
  end

  def self.require(*groups)
    groups = [:default] if groups.empty?
    groups.each do |group|
      (AUTOREQUIRES[group.to_sym] || []).each do |file, explicit|
        if explicit
          Kernel.require file
        else
          begin
            Kernel.require file
          rescue LoadError
          end
        end
      end
    end
  end

  # Set up load paths unless this file is being loaded after the Bundler gem
  setup unless defined?(Bundler::GEM_LOADED)
end
