defaults: &defaults
  sections:
    a:
      title: Introduction
    b: 
      title: Lesson
    c: 
      title: Student Work
    d: 
      title: Results
    e: 
      title: Conclusion
  
development: 
  <<: *defaults
  
test: &test
  <<: *defaults

cucumber: 
  <<: *test

production:
  <<: *defaults