base: &base
  storage: s3
  s3_credentials:
    access_key_id: ''
    secret_access_key: ''
    bucket: ''

development:
  <<: *base

test:
  <<: *base

cucumber:
  <<: *base

production:
  storage: s3
  s3_credentials:
    access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>
    bucket: <%= ENV['S3_BUCKET'] %>
