theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: center
theme_advanced_statusbar_location: none
orig_theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - uploadimage
plugins:
  - fullscreen
  - uploadimage
  - paste
uploadimage_form_url: /wysihat_files
theme_advanced_buttons1:
  - bold
  - italic
  - underline
  - '|'
  - sup
  - sub
  - '|'
  - bullist
  - numlist
  - '|'
  - link
  - image
  - uploadimage
  - '|'
  - pastetext
  - pasteword
  - selectall
  - '|'
  - justifyleft
  - justifycenter
  - justifyright
theme_advanced_buttons2:
theme_advanced_buttons3:
