plugins:
  - fullscreen
  - paste
  - image
  - lists
  - link
images_upload_url: '/wysihat_files'
automatic_uploads: true
toolbar: bold italic underline | superscript subscript | bullist numlist | link image | pastetext pasteword selectall | alignleft alignjustify alignright | fullscreen
branding: false
menubar: false
resize: false
statusbar: false

